name: Run Attendance Check

on:
  schedule:
    - cron: '0 7 * * 1-5'  # Run at 09:00 UTC+2 every weekday
    - cron: '30 11 * * 1-5' # Run at 13:30 UTC+2 every weekday

jobs:
  run_attendance_check:
    name: Run Attendance Check Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.4.1  # Use the actual latest version

      - name: Set up Python
        uses: actions/setup-python@v4.0.0  # Use the actual latest version
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Attendance Script
        env:
          MOODLE_USERNAME: ${{ secrets.MOODLE_USERNAME }}
          MOODLE_PASSWORD: ${{ secrets.MOODLE_PASSWORD }}
        run: python attendance.py
