name: Run Attendance Check

on:
  schedule:
    - cron: '0 7 * * 1-5'  # Run at 09:00 UTC+2 every weekday
    - cron: '30 11 * * 1-5' # Run at 13:30 UTC+2 every weekday

jobs:
  run_attendance_check:
    runs-on: ubuntu-latest
    name: Run Attendance Check Job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: 'latest'  # Ensure we're using a version compatible with geckodriver 0.34.0

      - name: Install geckodriver
        run: |
          GECKODRIVER_VERSION="0.34.0"
          wget https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
          tar -xzf geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium==4.20.0  # Match the version with local

      - name: Check Firefox and geckodriver versions
        run: |
          firefox --version
          geckodriver --version

      - name: Run Attendance Script
        env:
          MOODLE_USERNAME: ${{ secrets.MOODLE_USERNAME }}
          MOODLE_PASSWORD: ${{ secrets.MOODLE_PASSWORD }}
        run: python attendance.py

      - name: Upload geckodriver log
        if: always()  # This will upload the log regardless of success or failure
        uses: actions/upload-artifact@v2
        with:
          name: geckodriver-logs
          path: geckodriver.log
